# Generated by Django 3.2.4 on 2022-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='location', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='name', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telephone',
            field=models.IntegerField(default='1234'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='benjabenjita@abejita.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='benja benjita', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='benjadelcap', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(default='234'),
            preserve_default=False,
        ),
    ]
