# Generated by Django 3.2.4 on 2022-09-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220928_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='RestName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='UserName',
        ),
    ]
