# Generated by Django 3.2.4 on 2022-09-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220928_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='description',
            new_name='descrip',
        ),
    ]
