# Generated by Django 4.1.2 on 2022-10-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_available_tables_restaurant_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='RestName',
            new_name='restName',
        ),
    ]
